spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    kubernetes:
      loadbalancer:
        mode: service

server:
  port: 8100

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost
